<?php

namespace Database\Seeders;

use App\Models\Configuration\Company\Company;
use App\Models\Payroll\PayrollSalaryHead;
use Illuminate\Database\Seeder;

class PayrollSalaryHeadSeeder extends Seeder
{
    public function run(): void
    {
        $company = Company::first();
        if (!$company) {
            return;
        }

        $heads = [
            // Gross – Earnings
            [
                'name'                 => 'Basic Salary',
                'code'                 => 'BASIC',
                'identification_type'  => 'basic',
                'category'             => 'gross',
                'is_basic_linked'      => false,
                'basic_ratio'          => null,
                'is_variable'          => false,
                'is_taxable'           => false,
                'tax_calculation_type' => 'none',
                'tax_value'            => null,
                'position'             => 1,
            ],
            [
                'name'                 => 'House Rent Allowance',
                'code'                 => 'HRA',
                'identification_type'  => 'lfa',
                'category'             => 'gross',
                'is_basic_linked'      => true,
                'basic_ratio'          => 50.00,
                'is_variable'          => false,
                'is_taxable'           => false,
                'tax_calculation_type' => 'none',
                'tax_value'            => null,
                'position'             => 2,
            ],
            [
                'name'                 => 'Medical Allowance',
                'code'                 => 'MED',
                'identification_type'  => 'other',
                'category'             => 'gross',
                'is_basic_linked'      => true,
                'basic_ratio'          => 10.00,
                'is_variable'          => false,
                'is_taxable'           => false,
                'tax_calculation_type' => 'none',
                'tax_value'            => null,
                'position'             => 3,
            ],
            [
                'name'                 => 'Conveyance Allowance',
                'code'                 => 'CONV',
                'identification_type'  => 'other',
                'category'             => 'gross',
                'is_basic_linked'      => false,
                'basic_ratio'          => null,
                'is_variable'          => false,
                'is_taxable'           => false,
                'tax_calculation_type' => 'none',
                'tax_value'            => null,
                'position'             => 4,
            ],
            [
                'name'                 => 'Special Allowance',
                'code'                 => 'SPEC',
                'identification_type'  => 'other',
                'category'             => 'gross',
                'is_basic_linked'      => false,
                'basic_ratio'          => null,
                'is_variable'          => false,
                'is_taxable'           => false,
                'tax_calculation_type' => 'none',
                'tax_value'            => null,
                'position'             => 5,
            ],

            // Benefits
            [
                'name'                 => 'Festival Bonus',
                'code'                 => 'FEST-BONUS',
                'identification_type'  => 'other',
                'category'             => 'benefit',
                'is_basic_linked'      => true,
                'basic_ratio'          => 100.00,
                'is_variable'          => false,
                'is_taxable'           => false,
                'tax_calculation_type' => 'none',
                'tax_value'            => null,
                'position'             => 6,
            ],
            [
                'name'                 => 'Annual Performance Bonus',
                'code'                 => 'PERF-BONUS',
                'identification_type'  => 'other',
                'category'             => 'benefit',
                'is_basic_linked'      => false,
                'basic_ratio'          => null,
                'is_variable'          => true,
                'is_taxable'           => false,
                'tax_calculation_type' => 'none',
                'tax_value'            => null,
                'position'             => 7,
            ],
            [
                'name'                 => 'Mobile Allowance',
                'code'                 => 'MOBILE',
                'identification_type'  => 'other',
                'category'             => 'benefit',
                'is_basic_linked'      => false,
                'basic_ratio'          => null,
                'is_variable'          => false,
                'is_taxable'           => false,
                'tax_calculation_type' => 'none',
                'tax_value'            => null,
                'position'             => 8,
            ],
            [
                'name'                 => 'Internet Allowance',
                'code'                 => 'INTERNET',
                'identification_type'  => 'other',
                'category'             => 'benefit',
                'is_basic_linked'      => false,
                'basic_ratio'          => null,
                'is_variable'          => false,
                'is_taxable'           => false,
                'tax_calculation_type' => 'none',
                'tax_value'            => null,
                'position'             => 9,
            ],
            [
                'name'                 => 'Lunch Allowance',
                'code'                 => 'LUNCH',
                'identification_type'  => 'other',
                'category'             => 'benefit',
                'is_basic_linked'      => false,
                'basic_ratio'          => null,
                'is_variable'          => false,
                'is_taxable'           => false,
                'tax_calculation_type' => 'none',
                'tax_value'            => null,
                'position'             => 10,
            ],

            // Deductions
            [
                'name'                 => 'Provident Fund (Employee)',
                'code'                 => 'PF-EMP',
                'identification_type'  => 'pf_employee',
                'category'             => 'deduction',
                'is_basic_linked'      => true,
                'basic_ratio'          => 10.00,
                'is_variable'          => false,
                'is_taxable'           => false,
                'tax_calculation_type' => 'none',
                'tax_value'            => null,
                'position'             => 11,
            ],
            [
                'name'                 => 'Provident Fund (Employer)',
                'code'                 => 'PF-EMPLR',
                'identification_type'  => 'pf_employer',
                'category'             => 'benefit',
                'is_basic_linked'      => true,
                'basic_ratio'          => 10.00,
                'is_variable'          => false,
                'is_taxable'           => false,
                'tax_calculation_type' => 'none',
                'tax_value'            => null,
                'position'             => 12,
            ],
            [
                'name'                 => 'PF Employer Net Deduction',
                'code'                 => 'PF-EMPLR-DED',
                'identification_type'  => 'pf_employer_deduction',
                'category'             => 'deduction',
                'is_basic_linked'      => true,
                'basic_ratio'          => 10.00,
                'is_variable'          => false,
                'is_taxable'           => false,
                'tax_calculation_type' => 'none',
                'tax_value'            => null,
                'position'             => 13,
            ],
            [
                'name'                 => 'Income Tax (TDS)',
                'code'                 => 'TDS',
                'identification_type'  => 'other',
                'category'             => 'deduction',
                'is_basic_linked'      => false,
                'basic_ratio'          => null,
                'is_variable'          => true,
                'is_taxable'           => true,
                'tax_calculation_type' => 'percentage',
                'tax_value'            => 10.00,
                'position'             => 14,
            ],
            [
                'name'                 => 'Absence Deduction',
                'code'                 => 'ABS-DED',
                'identification_type'  => 'other',
                'category'             => 'deduction',
                'is_basic_linked'      => false,
                'basic_ratio'          => null,
                'is_variable'          => true,
                'is_taxable'           => false,
                'tax_calculation_type' => 'none',
                'tax_value'            => null,
                'position'             => 15,
            ],
            [
                'name'                 => 'Late Deduction',
                'code'                 => 'LATE-DED',
                'identification_type'  => 'other',
                'category'             => 'deduction',
                'is_basic_linked'      => false,
                'basic_ratio'          => null,
                'is_variable'          => true,
                'is_taxable'           => false,
                'tax_calculation_type' => 'none',
                'tax_value'            => null,
                'position'             => 16,
            ],

            // Adjustments
            [
                'name'                 => 'Salary Advance Recovery',
                'code'                 => 'ADV-REC',
                'identification_type'  => 'other',
                'category'             => 'adjustment',
                'is_basic_linked'      => false,
                'basic_ratio'          => null,
                'is_variable'          => true,
                'is_taxable'           => false,
                'tax_calculation_type' => 'none',
                'tax_value'            => null,
                'position'             => 17,
            ],
            [
                'name'                 => 'Arrear Payment',
                'code'                 => 'ARREAR',
                'identification_type'  => 'other',
                'category'             => 'adjustment',
                'is_basic_linked'      => false,
                'basic_ratio'          => null,
                'is_variable'          => true,
                'is_taxable'           => false,
                'tax_calculation_type' => 'none',
                'tax_value'            => null,
                'position'             => 18,
            ],
        ];

        foreach ($heads as $data) {
            PayrollSalaryHead::updateOrCreate(
                ['company_id' => $company->id, 'code' => $data['code']],
                array_merge($data, [
                    'company_id'      => $company->id,
                    'mode'            => 'cash',
                    'gl_prefix_type'  => 'static',
                    'gl_account_code' => null,
                    'is_active'       => true,
                ])
            );
        }
    }
}
