<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>{{ $title }}</title>
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { font-family: DejaVu Sans, Arial, sans-serif; font-size: 11px; color: #333; padding: 20px; }
        .header { margin-bottom: 14px; border-bottom: 2px solid #e5e7eb; padding-bottom: 10px; }
        .header h1 { font-size: 16px; font-weight: 700; color: #111; }
        .header p  { font-size: 10px; color: #888; margin-top: 3px; }
        table { width: 100%; border-collapse: collapse; }
        thead tr { background: #1e293b; color: #fff; }
        thead th { padding: 7px 10px; text-align: left; font-size: 10px; font-weight: 600; letter-spacing: .4px; text-transform: uppercase; }
        tbody tr:nth-child(even) { background: #f8fafc; }
        tbody tr:nth-child(odd)  { background: #ffffff; }
        tbody td { padding: 6px 10px; border-bottom: 1px solid #e5e7eb; }
        .footer { margin-top: 12px; font-size: 9px; color: #aaa; text-align: right; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title }}</h1>
        <p>Exported on {{ now()->format('d M Y, H:i:s') }} &nbsp;|&nbsp; Total records: {{ count($rows) }}</p>
    </div>

    <table>
        <thead>
            <tr>
                @foreach ($columns as $label)
                    <th>{{ $label }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @forelse ($rows as $row)
                <tr>
                    @foreach (array_keys($columns) as $key)
                        <td>{{ $row[$key] ?? '' }}</td>
                    @endforeach
                </tr>
            @empty
                <tr>
                    <td colspan="{{ count($columns) }}" style="text-align:center;padding:20px;color:#888;">
                        No records found.
                    </td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">Generated by {{ config('app.name') }}</div>
</body>
</html>
